source 'https://ruby.taobao.org'



gem 'rails', '4.2.0'

gem 'sqlite3', '1.3.9'

gem 'sass-rails', '5.0.0'

gem 'uglifier', '2.5.3'

gem 'coffee-rails', '4.1.0'


gem 'jquery-rails', '4.0.0'

gem 'turbolinks', '2.3.0'

gem 'jbuilder', '2.2.3'

gem 'sdoc', '0.4.0', group: :doc


group :development, :test do
  gem 'byebug', '3.4.0'
  gem 'web-console', '2.0.0'
  gem 'spring', '1.1.3'
end

