# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad2c3a90c9d339db2ab72dff676b88e37da0e27c961402c03f4bb8007c2d3ba30e8f63b6837ccb0287b0461dd1e2bc924ca1d4693b4a52f40da5f53e119a704

test:
  secret_key_base: 36bd69b63d3dd771bebba1eae27e6c609d2d91409af4342894d091c680fa3d4f130b55b922172c0280234e2aee4f4e79d661f90d4886257283cef591befd2cf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
