# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55ae18c68a5749272101fc16a78d4ae794f22c17ed77dac087a452f74461fd40f999e78a962903a194b334fbbb9e15fdb33ef833018d0f7f888213fa6ed3e3bd

test:
  secret_key_base: 5b890a73789099583f55a1ef538c15be34c370ac4b25eaf42b62c79fd536abc3a4865f2a169e4000b804cc9af40936e55ed182b6cb00742652c32d8a66a4bc23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
