source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'bcrypt'
gem 'bootstrap-sass'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'rails-html-sanitizer'
gem 'sdoc', '~> 0.4.0',          group: :doc

group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
  gem 'web-console'
  gem 'spring'
end

group :test do
    gem 'minitest-reporters'
    gem 'mini_backtrace',     '0.1.3'
    gem 'guard-minitest',     '2.3.1'
end
